[package]
name = "gdl90"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
chrono = "0.4.39"
dotenvy = "0.15.7"
futures = "0.3.31"
futures-util = "0.3.31"
log = "0.4.22"
pretty_env_logger = "0.5.0"
tokio = { version = "1.42.0", features = ["full"] }
